### ISSUE TITLE
Issue with mtcp_epoll_wait and mtcp_read

### ISSUE THREAD

**Issue by andreaskipf** [eunyoung14/mtcp#167] opened 2017-12-06 15:45 UTC
We're trying to integrate mTCP into our application. We noticed an issue with mtcp_epoll_wait in combination with mtcp_read:
mtcp_epoll_wait returns an EPOLLIN event but mtcp_read (which we call immediately after we've received the event) doesn't find any data to read (i.e., returns -1 with the error code EAGAIN). When sleeping for 100 microseconds before calling mtcp_read, it works fine.

There seems to be some sort of a race condition. Can you explain how epoll works internally and do you have any idea how we can debug this? We couldn't figure it out from the code.

Thanks!

**Comment by ajamshed** [comment] 2017-12-07 23:46
andreaskipf,

That's weird. I see that there is one possibility why this may happen. A TCP payload arrives that is within the TCP recv window but out-of-order. Can you please check if the issue goes away if you modify [line 605](https://github.com/eunyoung14/mtcp/blob/103e192b8d6f3636e0bb9cb6e2a0392290295275/mtcp/src/tcp_in.c#L605) of [tcp_in.c](https://github.com/eunyoung14/mtcp/blob/master/mtcp/src/tcp_in.c) to 
`if (cur_stream->state == TCP_ST_ESTABLISHED && rcvvar->rcvbuf->merged_len > 0) {` 

The epoll events are transferred from the mTCP layer to the app layer in the form of event objects. The 'if' condition (if true) raises the ``read`` event whose logic is implemented in ``eventpoll.c``.

**Comment by andreaskipf** [comment] 2017-12-08 14:11
Thanks for getting back to us, ajamshed.

I added that condition but it unfortunately didn't make any difference. This 'if' evaluates to true 6 times in both cases.

Let me elaborate a little bit on our setup:
We're using [pgbench](https://www.postgresql.org/docs/current/static/pgbench.html) as the client. So the client talks regular TCP and only the (database) server uses mTCP. We're sending 100 read transactions, which successfully complete but are very slow since we need to re-try reading the input many times per EPOLLIN event.

I assume there's a bug in our code. I'll update this thread once we've resolved it.

**Comment by ajamshed** [comment] 2017-12-08 17:57
Hmm. Let me know when you find the root cause of the problem. Thanks

**Comment by bglasber** [comment] 2018-03-18 21:21
Hi all,

We are experiencing the same issue... @andreaskipf , did you determine if it was a bug in your code?

In our setup, both the client and server are using mTCP, both sides using the epoll interface like the epwget example. If I configure a sleep doing an mtcp_recv on EPOLLIN, (10 ms), we generally receive all the messages and complete successfully (albeit slowly). If I reduce this sleep or remove it, then mtcp_recv will not pick up the packets (EAGAIN) despite getting EPOLLIN.

I've instrumented both the client and server to show the mtcp_recv/mtcp_write calls we are making to ensure that we are actually writing all of the data. Here are some logs that illustrate the problem --- I will show only the involved threads from either side to make it easier to follow.

We are doing repeated PUT requests in a custom key-value store.

The request format is:
[int32: num_keys] [int32: key]* [int32: num_vals] ([int32: str_len] [char: char]*)*

It returns:
[int32: ret_code]

Client-side, thread 24712:
```
I0318 16:55:57.361266 24712 mtcp_rpc_hack_client_driver.cpp:168] Client 6 loading from 7846 to 7851
I0318 16:55:57.361295 24712 mtcp.cpp:8] Sending int:100
I0318 16:55:57.361306 24712 mtcp.cpp:12] mtcp_write( 0x7f8c100008e0, 1, 0x7f8c26df2570, 4) 
24712 Stream 0: mtcp_write( 1, 0x7f8c26df2570, 4 )
24712 Stream 0: mtcp_write() returning 4
I0318 16:55:57.361325 24712 mtcp.cpp:21] Sent 4 out of 4 bytes for int!
I0318 16:55:57.361331 24712 mtcp.cpp:25] Sent int:100
I0318 16:55:57.361361 24712 mtcp.cpp:8] Sending int:5
I0318 16:55:57.361368 24712 mtcp.cpp:12] mtcp_write( 0x7f8c100008e0, 1, 0x7f8c26df24b0, 4) 
24712 Stream 0: mtcp_write( 1, 0x7f8c26df24b0, 4 )
24712 Stream 0: mtcp_write() returning 4
I0318 16:55:57.361403 24712 mtcp.cpp:21] Sent 4 out of 4 bytes for int!
I0318 16:55:57.361409 24712 mtcp.cpp:25] Sent int:5
I0318 16:55:57.361423 24712 mtcp.cpp:8] Sending int:7846
I0318 16:55:57.361428 24712 mtcp.cpp:12] mtcp_write( 0x7f8c100008e0, 1, 0x7f8c26df24b0, 4) 
24712 Stream 0: mtcp_write( 1, 0x7f8c26df24b0, 4 )
24712 Stream 0: mtcp_write() returning 4
I0318 16:55:57.361452 24712 mtcp.cpp:21] Sent 4 out of 4 bytes for int!

< ---- SNIP: sends other keys and values per the format above --- >

I0318 16:55:57.362287 24712 mtcp.cpp:8] Sending int:10
I0318 16:55:57.362291 24712 mtcp.cpp:12] mtcp_write( 0x7f8c100008e0, 1, 0x7f8c26df2490, 4) 
24712 Stream 0: mtcp_write( 1, 0x7f8c26df2490, 4 )
24712 Stream 0: mtcp_write() returning 4
I0318 16:55:57.362299 24712 mtcp.cpp:21] Sent 4 out of 4 bytes for int!
I0318 16:55:57.362303 24712 mtcp.cpp:25] Sent int:10
I0318 16:55:57.362308 24712 mtcp.cpp:33] mtcp_write( 0x7f8c100008e0, 1, 0x7f8c100d5440, 10 )
24712 Stream 0: mtcp_write( 1, 0x7f8c100d5440, 10 )
24712 Stream 0: mtcp_write() returning 10
I0318 16:55:57.362315 24712 mtcp.cpp:42] Sent 10 out of 10 bytes for string!
I0318 16:55:57.362318 24712 mtcp.cpp:45] Sent str:6ttttttttt
I0318 16:55:57.362323 24712 mtcp_rpc_hack_client_driver.cpp:188] Client 6 done issuing LOAD

< ---- In here it should get a response from the server, but it never does ---->

F0318 16:56:27.362030 24712 mtcp_rpc_hack_client_driver.cpp:480] Socket timed out: 1
```

Server-side, thread 13376:
```
I0318 16:55:54.464205 13376 mtcp_rpc_server.cpp:173] Received EPOLLIN on core: 6
I0318 16:55:54.464226 13376 mtcp_rpc_server.cpp:232] Message from 6
13376 Stream 0: mtcp_recv( 2, 0x7f36c35f4974, 4, 0 ) EAGAIN no buff
I0318 16:55:54.464335 13376 mtcp_rpc_server.cpp:467] Client 6 got EAGAIN on mtcp_read.
I0318 16:55:54.464414 13376 mtcp_rpc_server.cpp:173] Received EPOLLIN on core: 6
I0318 16:55:54.464452 13376 mtcp_rpc_server.cpp:232] Message from 6
13376 Stream 0: mtcp_recv( 2, 0x7f36c35f4974, 4, 0 ) still some data left setting EPOLLIN
13376 Stream 0: mtcp_recv( 2, 0x7f36c35f4974, 4, 0 )
13376 Stream 0: mtcp_recv() returning 4
I0318 16:55:54.464527 13376 mtcp_rpc_server.cpp:245] Set func for 6 to: 100
13376 Stream 0: mtcp_recv( 2, 0x7f36c35f4974, 4, 0 ) still some data left setting EPOLLIN
13376 Stream 0: mtcp_recv( 2, 0x7f36c35f4974, 4, 0 )
13376 Stream 0: mtcp_recv() returning 4
I0318 16:55:54.464644 13376 mtcp_rpc_server.cpp:304] Client 6 need to read 5 ints.
13376 Stream 0: mtcp_recv( 2, 0x7f36c35f4974, 4, 0 ) still some data left setting EPOLLIN
13376 Stream 0: mtcp_recv( 2, 0x7f36c35f4974, 4, 0 )
13376 Stream 0: mtcp_recv() returning 4
I0318 16:55:54.464707 13376 mtcp_rpc_server.cpp:315] Client 6 read int: 7846
13376 Stream 0: mtcp_recv( 2, 0x7f36c35f4974, 4, 0 )
13376 Stream 0: mtcp_recv() returning 4
I0318 16:55:54.464773 13376 mtcp_rpc_server.cpp:315] Client 6 read int: 7847
13376 Stream 0: mtcp_recv( 2, 0x7f36c35f4974, 4, 0 ) still some data left setting EPOLLIN
13376 Stream 0: mtcp_recv( 2, 0x7f36c35f4974, 4, 0 )
13376 Stream 0: mtcp_recv() returning 4
I0318 16:55:54.464833 13376 mtcp_rpc_server.cpp:315] Client 6 read int: 7848
13376 Stream 0: mtcp_recv( 2, 0x7f36c35f4974, 4, 0 ) still some data left setting EPOLLIN
13376 Stream 0: mtcp_recv( 2, 0x7f36c35f4974, 4, 0 )
13376 Stream 0: mtcp_recv() returning 4
I0318 16:55:54.464941 13376 mtcp_rpc_server.cpp:315] Client 6 read int: 7849
13376 Stream 0: mtcp_recv( 2, 0x7f36c35f4974, 4, 0 ) still some data left setting EPOLLIN
13376 Stream 0: mtcp_recv( 2, 0x7f36c35f4974, 4, 0 )
13376 Stream 0: mtcp_recv() returning 4
I0318 16:55:54.464959 13376 mtcp_rpc_server.cpp:315] Client 6 read int: 7850
13376 Stream 0: mtcp_recv( 2, 0x7f36c35f4974, 4, 0 ) still some data left setting EPOLLIN
13376 Stream 0: mtcp_recv( 2, 0x7f36c35f4974, 4, 0 )
13376 Stream 0: mtcp_recv() returning 4
I0318 16:55:54.465059 13376 mtcp_rpc_server.cpp:326] Client 6 needs to read 5 strs.
13376 Stream 0: mtcp_recv( 2, 0x7f36c35f4974, 4, 0 ) still some data left setting EPOLLIN
13376 Stream 0: mtcp_recv( 2, 0x7f36c35f4974, 4, 0 )
13376 Stream 0: mtcp_recv() returning 4
I0318 16:55:54.465140 13376 mtcp_rpc_server.cpp:342] Client 6, string: 0, needs to read a str of len 10
I0318 16:55:54.465147 13376 mtcp_rpc_server.cpp:344] Client 6, string: 0, trying to mtcp recv with a len of 10
13376 Stream 0: mtcp_recv( 2, 0x7f369c0db0b0, 10, 0 ) still some data left setting EPOLLIN
13376 Stream 0: mtcp_recv( 2, 0x7f369c0db0b0, 10, 0 )
13376 Stream 0: mtcp_recv() returning 10
60318 16:55:54.465252 13376 mtcp_rpc_server.cpp:353] Client 6, read string: 6ccccccccc
13376 Stream 0: mtcp_recv( 2, 0x7f36c35f4974, 4, 0 ) still some data left setting EPOLLIN
13376 Stream 0: mtcp_recv( 2, 0x7f36c35f4974, 4, 0 )
13376 Stream 0: mtcp_recv() returning 4
I0318 16:55:54.465328 13376 mtcp_rpc_server.cpp:342] Client 6, string: 1, needs to read a str of len 10
I0318 16:55:54.465335 13376 mtcp_rpc_server.cpp:344] Client 6, string: 1, trying to mtcp recv with a len of 10
13376 Stream 0: mtcp_recv( 2, 0x7f369c0db060, 10, 0 ) still some data left setting EPOLLIN
13376 Stream 0: mtcp_recv( 2, 0x7f369c0db060, 10, 0 )
13376 Stream 0: mtcp_recv() returning 10
60318 16:55:54.465364 13376 mtcp_rpc_server.cpp:353] Client 6, read string: 6wwwwwwwww
13376 Stream 0: mtcp_recv( 2, 0x7f36c35f4974, 4, 0 )
13376 Stream 0: mtcp_recv() returning 4
I0318 16:55:54.465407 13376 mtcp_rpc_server.cpp:342] Client 6, string: 2, needs to read a str of len 10
I0318 16:55:54.465420 13376 mtcp_rpc_server.cpp:344] Client 6, string: 2, trying to mtcp recv with a len of 10
13376 Stream 0: mtcp_recv( 2, 0x7f369c0db010, 10, 0 ) still some data left setting EPOLLIN
13376 Stream 0: mtcp_recv( 2, 0x7f369c0db010, 10, 0 )
13376 Stream 0: mtcp_recv() returning 10
I0318 16:55:54.465473 13376 mtcp_rpc_server.cpp:353] Client 6, read string: 6ccccccccc
13376 Stream 0: mtcp_recv( 2, 0x7f36c35f4974, 4, 0 ) still some data left setting EPOLLIN
13376 Stream 0: mtcp_recv( 2, 0x7f36c35f4974, 4, 0 )
13376 Stream 0: mtcp_recv() returning 4
I0318 16:55:54.465497 13376 mtcp_rpc_server.cpp:342] Client 6, string: 3, needs to read a str of len 10
I0318 16:55:54.465539 13376 mtcp_rpc_server.cpp:344] Client 6, string: 3, trying to mtcp recv with a len of 10
13376 Stream 0: mtcp_recv( 2, 0x7f369c0db100, 10, 0 )
13376 Stream 0: mtcp_recv() returning 10
I0318 16:55:54.465553 13376 mtcp_rpc_server.cpp:353] Client 6, read string: 6rrrrrrrrr
13376 Stream 0: mtcp_recv( 2, 0x7f36c35f4974, 4, 0 ) EAGAIN no buff
I0318 16:55:54.465572 13376 mtcp_rpc_server.cpp:467] Client 6 got EAGAIN on mtcp_read.
I0318 16:55:54.465577 13376 mtcp_rpc_server.cpp:338] Client 6 not ready to read yet!
I0318 16:55:54.465582 13376 mtcp_rpc_server.cpp:173] Received EPOLLIN on core: 6
I0318 16:55:54.465586 13376 mtcp_rpc_server.cpp:232] Message from 6
13376 Stream 0: mtcp_recv( 2, 0x7f36c35f4974, 4, 0 ) EAGAIN no buff
I0318 16:55:54.465600 13376 mtcp_rpc_server.cpp:467] Client 6 got EAGAIN on mtcp_read.
I0318 16:55:54.465615 13376 mtcp_rpc_server.cpp:338] Client 6 not ready to read yet!
```

The mtcp_recv log messages are from instrumentation I put directly into mtcp.

The relevant ones:

```
    /* return EAGAIN if no receive buffer */
    if (socket->opts & MTCP_NONBLOCK) {
        if (!rcvvar->rcvbuf || rcvvar->rcvbuf->merged_len == 0) {
            TRACE_CONFIG("%ld Stream %d: mtcp_recv( %d, %p, %ld, %d ) EAGAIN no buff\n", syscall(__NR_gettid), cur_stream->id, sockid, (void *) buf, len, flags);
            errno = EAGAIN;
            return -1;

        }
    }

    ...

       if (socket->epoll & MTCP_EPOLLIN) {
        if (!(socket->epoll & MTCP_EPOLLET) && rcvvar->rcvbuf->merged_len > 0) {
            TRACE_CONFIG("%ld Stream %d: mtcp_recv( %d, %p, %ld, %d ) still some data left setting EPOLLIN\n", syscall(__NR_gettid), cur_stream->id, sockid, (void *) buf, len, flags);
            event_remaining = TRUE;
        }
    }

```
In mtcp_recv in api.c.

Here's our read loop on the server-side:
```
  int nevents;
  int do_accept = 0;
  int i;
  while (1) {
    nevents = mtcp_epoll_wait(mctx, ep, events, max_events, -1);
    if (nevents < 0) {
      if (errno != EINTR) {
        PLOG(WARNING) << "mtcp_epoll_wait";
      }
      break;
    }

    do_accept = 0;

    for (i = 0; i < nevents; i++) {
      if (events[i].data.sockid == listener) {
        do_accept = 1;
      } else if (events[i].events & MTCP_EPOLLERR) {
        DVLOG(20) << "Got MTCP_EPOLLERR";
        int err;
        socklen_t len = sizeof(err);
        if (mtcp_getsockopt(mctx, events[i].data.sockid, SOL_SOCKET, SO_ERROR,
                            (void *)&err, &len) == 0) {
          if (err != ETIMEDOUT) {
            /* Close connection */
            mtcp_epoll_ctl(mctx, ep, MTCP_EPOLL_CTL_DEL, events[i].data.sockid,
                           NULL);
            mtcp_close(mctx, events[i].data.sockid);
            exit(-1);
          } else {
            // Timeouts should be disabled
            DVLOG(20) << "Got timed out error";
          }
        } else {
          DLOG(ERROR) << "Unable to get sockopt";
          exit(-1);
        }

      } else if (events[i].events & MTCP_EPOLLOUT) {
        DVLOG(20) << "Received EPOLLOUT request";
        LOG( INFO ) << "Received EPOLLOUT on core: " << core;
      } else if (events[i].events & MTCP_EPOLLIN) {
        DVLOG(20) << "Received EPOLLIN request";
        LOG( INFO ) << "Received EPOLLIN on core: " << core;
        
        ctx.sockfd = events[i].data.sockid;
        //Process whatever we got
        do_async_req_process(&ctx);
      }
    }

    if (do_accept) {
      LOG( INFO ) << "Told to accept new connection, core: " << core;
      while (1) {
        struct mtcp_epoll_event ev;
        int c;
        c = mtcp_accept(mctx, listener, NULL, NULL);
        if (c >= 0) {
          ev.events = MTCP_EPOLLIN;
          ev.data.sockid = c;
          mtcp_setsock_nonblock(mctx, c);
          mtcp_epoll_ctl(mctx, ep, MTCP_EPOLL_CTL_ADD, c, &ev);
          LOG( INFO ) << "Told to accept new connection!";
          DVLOG(20) << "Accepted new connection, core: " << core;
        } else {
          break;
        }
      }
    }
  }
```

do_async_req_process keeps state about what it has done so far for the current request, reads as much data as it can from the socket before getting an EAGAIN using mtcp_recv, and then returns. if the current transaction is complete, it writes back the response and resets the tracked state.

As far as I can tell, we are using the API correctly. I took a  brief look through the mTCP code but I'm don't know too much about TCP stack internals, not sure I can be of much help there.

Do you have any insight into the cause of this issue, @ajamshed ?

**Comment by andreaskipf** [comment] 2018-03-19 03:01
Hi Brad, unfortunately we weren’t able to fix/track down the issue. Still
can’t say for sure whether there’s a bug on our side. We were trying to
port an existing code base. With regular TCP/epoll it works fine.

**Comment by ajamshed** [comment] 2018-03-19 19:16
Hi @andreaskipf ,

Is it possible that you can share your client and server code with us? I want to recreate the issue that you are facing in my machines here.

**Comment by bglasber** [comment] 2018-03-19 19:50
Yes, I can paste my code. I'll clean it up to a minimal working example and paste a link here today/tomorrow.

**Comment by andreaskipf** [comment] 2018-03-20 01:21
Unfortunately it is proprietary code that I’m not allowed to share. It is a
server-side implementation of the PostgreSQL wire protocol. I really hope
it’s the same issue that Brad faces (even though we’re using regular TCP on
the client side, namely a standard pqxx client). Once that’s fixed, I can
try the same fix on my side and report back to you.

**Comment by eunyoung14** [comment] 2018-06-23 10:10
Closing the issue since there was no activity for a while.

**Closed by eunyoung14** 2018-06-23 10:10 UTC
