### ISSUE TITLE
The epwget application has a bug possibly!

### ISSUE THREAD

**Issue by loveqingping** [eunyoung14/mtcp#67] opened 2016-05-20 03:31 UTC
In function HandleReadEvent, the code is shown below

```
                            wv->headerset = TRUE;
            wv->recv += (rd - (wv->resp_len - wv->header_len));
            rd = (wv->resp_len - wv->header_len);

                            pbuf += (rd - (wv->resp_len - wv->header_len));
```

Pointer pbuf doesn't move any more, It still points to the HTTP header, not the HTTP paryload!

**Comment by ajamshed** [comment] 2016-06-07 14:13
Apologies for responding this late. Can you please explain the problem in more detail? "pbuf not moving" does not make sense in this code snippet.

**Comment by lybmath** [comment] 2017-04-12 04:12
I think this is just a small issue caused by the order.

We found and fixed this problem some time ago. When we run epwget to get a very small file from the server, we found that the downloaded file had only a HTTP header without any file contents although the connection is finished successfully. 

Finally, we found the reason in the code snippet @loveqingping mentioned.
"rd = (wu->resp_len - wv->header_len);" should be put after "pbuf += (rd - (wv-resp_len -wv->header_len));". Otherwise, the expression (rd - (wv->resp_len - wv->header_len)) will always be 0, causing that the pbuf keeps unchanged.

**Comment by ajamshed** [comment] 2017-04-20 13:44
Thanks for pointing out the bug. It is now fixed.

**Closed by ajamshed** 2017-04-20 13:44 UTC

**Comment by loveqingping** [comment] 2017-11-23 13:18
@lybmath  Your English is good!
